In [1]:
import tensorflow as tf

In [13]:
tf.__version__

'2.16.1'

# Constants

In [14]:
hello =tf.constant("Hello")

In [15]:
print(hello)

tf.Tensor(b'Hello', shape=(), dtype=string)


In [16]:
tf.print(hello)

Hello


In [17]:
world =tf.constant("World")

In [19]:
helloworld = hello + " " + world
tf.print(helloworld)

Hello World


In [20]:
a = tf.constant(10)
b = tf.constant(20)
print(a, b)

tf.Tensor(10, shape=(), dtype=int32) tf.Tensor(20, shape=(), dtype=int32)


In [21]:
a = b

In [23]:
a+b

<tf.Tensor: shape=(), dtype=int32, numpy=40>

In [25]:
tf.print(a+b)

40


In [26]:
myarr = tf.fill((5,5),5)

In [28]:
myarr

<tf.Tensor: shape=(5, 5), dtype=int32, numpy=
array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])>

In [27]:
tf.print(myarr)

[[5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]
 [5 5 5 5 5]]


In [29]:
#return tensor as numpy array
myarr.numpy()

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [30]:
myarr.get_shape()

TensorShape([5, 5])

In [35]:
myarr1 = tf.constant([[1, 2],
                     [3, 4]])
tf.print(myarr1)

[[1 2]
 [3 4]]


In [34]:
myarr2 = tf.random.normal((3, 3), 0, 1)
tf.print(myarr2)

[[0.0876884535 -0.376684517 1.32821441]
 [-1.26698947 0.692535579 -1.20115948]
 [0.0934032947 0.0195678137 0.930552483]]


# Variables

In [43]:
var = tf.Variable(1, dtype=tf.int32)

In [44]:
var.assign(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=2>

In [41]:
var.assign_add(2)

<tf.Variable 'UnreadVariable' shape=() dtype=int32, numpy=4>

# Matrixs

In [46]:
#zero matrix
zero_matrix = tf.zeros(shape=(3,3), dtype=tf.float32)
ones_matrix = tf.ones(shape=(3,3), dtype=tf.float32)
rows, columns = zero_matrix.shape
identity_matrix = tf.eye(num_rows=rows, num_columns=columns, dtype=tf.float32)

In [47]:
zero_matrix.numpy()

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [48]:
ones_matrix.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [49]:
identity_matrix.numpy()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]], dtype=float32)

In [51]:
tf.reshape(identity_matrix, shape=(1,9)).numpy()

array([[1., 0., 0., 0., 1., 0., 0., 0., 1.]], dtype=float32)

In [59]:
mat = tf.constant([[1,2,3],
                  [4,5,6],
                  [7,8,9]], dtype=tf.float32)
mat.numpy()

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [60]:
tf.transpose(mat).numpy()

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]], dtype=float32)

In [61]:
tf.matmul(ones_matrix, mat).numpy()

array([[12., 15., 18.],
       [12., 15., 18.],
       [12., 15., 18.]], dtype=float32)

In [62]:
tf.multiply(ones_matrix, mat).numpy()

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

# Operations on tensorflow

In [63]:
W = tf.Variable(10, dtype=tf.int32)
b = tf.Variable(5, dtype=tf.int32)

def linear_model(x):
    return W*x+b

linear_model(x=[1,2,3,4,5,6,7]).numpy()

array([15, 25, 35, 45, 55, 65, 75])